version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - confluent

  kafka-0:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-0
    depends_on:
      - zookeeper
    ports:
      - "19093:19093"
    networks:
      - confluent
    volumes:
      - data-kafka-0:/var/lib/kafka/data
      - ./tls/kafka-0-creds:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-0:9092,EXTERNAL://localhost:19093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

      # SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka-0.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: "123456"
      KAFKA_SSL_KEY_PASSWORD: "123456"
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-0.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "123456"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_LISTENER_SECURITY_PROTOCOL: SSL
      #Авторизация
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SSL_PRINCIPAL_MAPPING_RULES: "RULE:^CN=([^,]*).*$/$1/,DEFAULT"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: >
        User:kafka-0;
        User:kafka-1;
        User:kafka-2;


  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    networks:
      - confluent
    volumes:
      - data-kafka-1:/var/lib/kafka/data
      - ./tls/kafka-1-creds:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      # SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka-1.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: "123456"
      KAFKA_SSL_KEY_PASSWORD: "123456"
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "123456"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_LISTENER_SECURITY_PROTOCOL: SSL
      #Авторизация
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SSL_PRINCIPAL_MAPPING_RULES: "RULE:^CN=([^,]*).*$/$1/,DEFAULT"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: >
        User:kafka-0;
        User:kafka-1;
        User:kafka-2;

  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - "39093:39093"
    networks:
      - confluent
    volumes:
      - data-kafka-2:/var/lib/kafka/data
      - ./tls/kafka-2-creds:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:39093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:39093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      # SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka-2.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: "123456"
      KAFKA_SSL_KEY_PASSWORD: "123456"
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "123456"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_LISTENER_SECURITY_PROTOCOL: SSL
      #Авторизация
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SSL_PRINCIPAL_MAPPING_RULES: "RULE:^CN=([^,]*).*$/$1/,DEFAULT"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: >
        User:kafka-0;
        User:kafka-1;
        User:kafka-2;
        
  # Конфигурация producer который пишет в topic-1
  app-producer-1:
    networks:
      - confluent
    volumes:
      - ./tls/app-producer-creds/:/etc/kafka/secrets/app-producer-creds/
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    build: .
    container_name: app-producer-1
    command:
      - "java"
      - "-jar"
      - "/app/producer.jar"
      - "kafka-0:9092" # адрес брокера
      - "topic-1"  # название топика

  # Конфигурация producer который пишет в topic-2
  app-producer-2:
    networks:
      - confluent
    volumes:
      - ./tls/app-producer-creds/:/etc/kafka/secrets/app-producer-creds/
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    build: .
    container_name: app-producer-2
    command:
      - "java"
      - "-jar"
      - "/app/producer.jar"
      - "kafka-0:9092" # адрес брокера
      - "topic-2"  # название топика

  # Конфигурация получателя из topic-1
  app-consumer-1:
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    networks:
      - confluent
    volumes:
      - ./tls/app-consumer-creds/:/etc/kafka/secrets/app-consumer-creds/
    build: .
    container_name: app-consumer-1
    command:
      - "java"
      - "-jar"
      - "/app/single-message-consumer.jar"
      - "kafka-0:9092" # адрес брокера
      - "group1"  # название consumer group
      - "topic-1"  # название топика

  # Конфигурация получателя из topic-2
  app-consumer-2:
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    networks:
      - confluent
    volumes:
      - ./tls/app-consumer-creds/:/etc/kafka/secrets/app-consumer-creds/
    build: .
    container_name: app-consumer-2
    command:
      - "java"
      - "-jar"
      - "/app/single-message-consumer.jar"
      - "kafka-0:9092" # адрес брокера
      - "group1"  # название consumer group
      - "topic-2"  # название топика

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: kafka-ui
    hostname: kafka-ui
    restart: always
    ports:
      - "127.0.0.1:8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "SSL Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka-0:9092,kafka-1:9092,kafka-2:9092"

      # SSL настройки
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SSL"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.kafka-0.truststore.jks"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "123456"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka-0.keystore.jks"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "123456"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD: "123456"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""

      # Оптимизация логов
      LOGGING_LEVEL_ROOT: "INFO"
      LOGGING_LEVEL_ORG_APACHE_KAFKA: "WARN"
    volumes:
      - ./tls/kafka-0-creds:/etc/kafka/secrets
    networks:
      - confluent

volumes:
  data-kafka-0:
  data-kafka-1:
  data-kafka-2:

networks:
  confluent:
